# Generated by Django 2.2.3 on 2019-12-04 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='listings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='listings.Listings', verbose_name='Объявление'),
        ),
    ]
