# Generated by Django 2.2.3 on 2021-05-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20191204_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
