# Generated by Django 2.2.3 on 2019-09-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'verbose_name_plural': 'объявления'},
        ),
    ]
