# Generated by Django 2.2.3 on 2021-05-25 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20191209_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='отображать'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=' дата'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='изображение 1'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='изображение 2'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='изображение 3'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='изображение 4'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='изображение 5'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='изображение 6'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='основное изображение'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Названия'),
        ),
    ]
