# Generated by Django 2.2.3 on 2021-05-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20190921_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': 'специалист', 'verbose_name_plural': 'специалисты'},
        ),
    ]
